apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: georedis
resources:
  - namespace.yaml
  - configmap.yaml
  - shard-0-americas.yaml
  - shard-1-europe.yaml
  - shard-2-asia.yaml
