apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-node-0-data
  namespace: geo-redisis
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 10Gi }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-node-1-data
  namespace: geo-redisis
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 10Gi }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-node-2-data
  namespace: geo-redisis
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 10Gi }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-node-3-data
  namespace: geo-redisis
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: { storage: 10Gi }